version: "2"

volumes:
  mysql:

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    command: ./proc-start web
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.1
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
